# NEVER use TAB in configuration file, use space
name: ssendeavour's simple blog
markdown: redcarpet
pygments: true

# curiously, only Shanghai and Chong are listed in http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
encoding: UTF-8

# date:   /:categories/:year/:month/:day/:title.html (default)
# pretty: /:categories/:year/:month/:day/:title/ (prefer no extension for greater portablility)
# none:   /:categories/:title.html
permalink: pretty

# enable pagination
# how many items should be displayed per page:
# pagination: 5

# destination of the pagination pages:
# paginate_path: "blog/page_:num"

maruku:
    use_tex: true
    use_divs: true
    png_engine: blahtex
    png_dir: images/latex
    png_url: /images/latex/


